services:
  madhonsite:
    container_name: madhonsite
    restart: unless-stopped
    build:
      context: ./Romulus.Web
      dockerfile: Dockerfile
    networks:
      - madhonsitenet
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_RUNNING_IN_CONTAINER : "true"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT : "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.madhon.entrypoints=web"
      - "traefik.http.routers.madhon.rule=Host(`madhon-192-168-1-70.nip.io`)"
      - "traefik.http.services.madhon.loadbalancer.server.port=8080"
      - "traefik.http.routers.madhonsecure.entrypoints=websecure"
      - "traefik.http.routers.madhonsecure.tls=true"
      - "traefik.http.routers.madhonsecure.rule=Host(`madhon-192-168-1-70.nip.io`)"
      - "traefik.http.middlewares.testHeader.headers.customresponseheaders.X-Custom-Response-Header=value"
      - "traefik.http.routers.madhon.middlewares=testHeader@docker"
      - "traefik.http.routers.madhonsecure.middlewares=testHeader@docker"

  traefikproxy:
    image: traefik:v2.8
    pull_policy: always
    restart: unless-stopped
    container_name: traefikproxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--log.filePath=/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/traefik/access.log"
      - "--certificatesresolvers.myresolver.acme.email=madhon@madhon.co.uk"
      - "--certificatesresolvers.myresolver.acme.storage=/docker/certs/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - madhonsitenet
    volumes:
      - ./docker/certs:/docker/certs
      - ./docker/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik-192-168-1-70.nip.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
    depends_on:
      - madhonsite

networks:
  madhonsitenet : {}
