name: RomulusWeb-CD
trigger: none
resources:
  pipelines:
   - pipeline: RomulusWeb-Build
     source: RomulusWeb-Build
     trigger:
      branches:
       include:
         - master         

variables:
  agentImage: "ubuntu-22.04"

stages:
- stage: Deploy
  displayName: "Deploy To DigitalOcean"
  jobs:
  - deployment: DODepoly
    displayName: 'Deploy to Digital Ocean'
    environment: Prod
    pool:
     vmImage: $(agentImage)
    strategy:
      runOnce:
        deploy:    
          steps:
            - task: DownloadPipelineArtifact@2
              displayName: 'Download Build Artifact'
              inputs:
                buildType: 'specific'
                project: '4be30c19-ce7f-46bc-94f9-f712d0faf9ba'
                definition: '13'
                buildVersionToDownload: 'latest'
                artifactName: 'drop'
                targetPath: '$(System.DefaultWorkingDirectory)/_MadhonCOMWebsite'
            - task: CopyFilesOverSSH@0
              displayName: 'Copy files to DigitalOcean'
              inputs:
                sshEndpoint: DigialOcean
                sourceFolder: '$(System.DefaultWorkingDirectory)/_MadhonCOMWebsite'
                targetFolder: '/home/madhon_webdeploy/files'
            - task: SSH@0
              displayName: 'Update Site Files'
              inputs:
                sshEndpoint: DigialOcean
                runOptions: inline
                inline: |
                  #!/bin/sh
                  WEBROOT=/var/www/madhon.co.uk
                  SOURCE=/home/madhon_webdeploy/files
                  echo "Deploying Artifact from Build ID - $(resources.pipeline.RomulusWeb-Build.runID)"
                  echo "Stopping site"
                  sudo systemctl stop madhonsite-kestrel.service
                  cd $SOURCE/output
                  echo "Unziping files"
                  unzip -oq $SOURCE/Romulus.Web.zip
                  echo "Copying files and resetting permissions"
                  sudo cp -r $SOURCE/output/* $WEBROOT
                  sudo chown -R www-data:www-data $WEBROOT
                  sudo /usr/bin/rm $WEBROOT/appsettings.Development.json
                  echo "Starting Site"
                  sudo systemctl start madhonsite-kestrel.service
