// Generated by CoffeeScript 1.7.1
(function() {
  var site;

  site = {};

  $(document).ready(function() {
    return site.initializeDialogs();
  });

  site.initializeDialogs = function() {};

}).call(this);

//# sourceMappingURL=site.map
